### ISSUE TITLE
Slackware 14.2 支持

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/netease_cloud_music_slackbuild#13]
把glib 的部分都去了，在Arch 上跑了下是没问题的，但是不知道打出来的包能不能在14.2 上正常跑。

比较尴尬的是Arch 里虽然跑着一个libvirtd，但是并没有slackware 的KVM……

分支只是个用于记录的demo，无其他用处。

**Comment by Arondight** [comment]
Ref #4

**Comment by nnnewb** [comment]
请求current用户测试
或者过几天我去搭个vbox跑一下current测一测
编译qt5真的好慢啊

**Comment by Arondight** [comment]
@nnnewb 我看看端午节在自己的KVM 上搞个current 吧，机器的CPU 和内存都比较富足，再者KVM 也比VBox 快一些。

**Comment by Arondight** [comment]
@nnnewb 我试了一下似乎有点问题

```
root@slackware64-current:/tmp/netease_cloud_music_slackbuild# netease-cloud-music 
netease-cloud-music: /lib64/libcrypto.so.1.0.0: no version information available (required by netease-cloud-music)
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, wayland, xcb.

Reinstalling the application may fix this problem.
Aborted
root@slackware64-current:/tmp/netease_cloud_music_slackbuild# 
```

qt5 我直接用的alien 打的[二进制包](http://www.slackware.com/~alien/slackbuilds/qt5/pkg64/current/)，不过build 都是sbo 上的，理论上和自己打的二进制包应该是等效的。

**Comment by Arondight** [comment]
@nnnewb 刚刚写了一个小工具[slackrebuild](https://github.com/slackwarecn/slackrebuild)，用来从现有的系统上重新构建出一个软件包的TXZ 安装包，你可以用这个工具在你的14.1 上抽出来已经安装的Qt5，然后安装一个current，把这个包装上试一下。

``` bash
slackrebuild qt5
```

我不敢确定alien 的源里没有少什么包，也不知道qt5 的slackbuild 会构建出几个包。你可以安装一个current 然后按照上面的方法试一下会不会出之前说的那个错误。

[这里](http://mirrors.ustc.edu.cn/slackware/slackware-iso/slackware-current-iso/)有current 的iso。

**Comment by nnnewb** [comment]
坐等libvirt安装中。

**Comment by nnnewb** [comment]
已跪，ipaddr-py又是一个googlecode上的源码包
今天还得干别的，改日再折腾current....

**Comment by Arondight** [comment]
你不用非得起KVM 啊，Qt5 可以直接从现有系统里抽出来，新系统基本没编译工作，起个VBox 就够用了

**Comment by Arondight** [comment]
要是你准备起libvirtd，你会发现你还需要搞一个virt-manager……

**Comment by Arondight** [comment]
已经提交 Merge Request #19 ，单独的Slackware 14.2 分支似乎不再必要，见 #17

**Comment by Arondight** [comment]
今天找别人测了一下，依旧是slackware 14.2 无法运行，报错见之前的回复

**Comment by lteyang** [comment]
大家好，我现在装的系统是slackware 14.2。 关于netease-cloud-music，我可以帮忙测试。但目前，我不是按这个slackbuild安装的。我是直接官网1.0.0版用deg2tgz转换后安装，需要库qt5，libxkbcommon,libcue(这个不知道有没有，看了你们的说明后加的），现在可以启动，但有问题，会出现“加载失败，网络错误”，播放本地文件也是这样，不知道什么原因。
PS: 用你们这个脚本安装，也是这样，可以启动，但播放音乐时报错。

关于上面那两个报错：
1.libcropty 0.9.0版本会有，1.0.0没有这个报错。
2.xcb，通过QT_QPA_PLATFORM_PLUGIN=1 netease-cloud-music 启动，我这边可以看到是缺少libxkbcommon这个库，你们可以试一下。

**Comment by Arondight** [comment]
_(:з」∠)_ 我手头还没有14.2，过几天装个试试

这脚本我都在Arch Linux 下面写的……

我在KVM 上的Current 上试了试，似乎报错依旧

**Comment by Arondight** [comment]
@lteyang 不知道你的Qt5 是怎么安装的？我是直接用alien 打好的包安装的，没有编译。

**Comment by lteyang** [comment]
@Arondight 
一样，也是alien的库

**Comment by lteyang** [comment]
我这边音乐播放时报错估计是qt5库的问题，我再尝试下看看

PS:十有八九，刚看了slackbuilds.org 里的qt5说明，我正在重新编译qt5

**Comment by Arondight** [comment]
@lteyang Qt5 编译非常耗时，建议有空再搞。

**Comment by lteyang** [comment]
@Arondight 机子挂着。。。我估计和chromium差不多，得一个晚上，明早估计就好了

**Comment by Arondight** [comment]
@lteyang 刚刚推了一个提交，同步上游版本1.0.0，麻烦在14.2 上试一下可以用吗？

**Comment by lteyang** [comment]
@Arondight 我编译好后，用你这个脚本重新安装试下。我原来也有用1.0.0试过，就差上面那个libcropty错误提示，其它都一样。

**Comment by Arondight** [comment]
@lteyang 我看了下，是因为缺少一个库`libxkbcommon-x11`，导致`libqxcb.so` 无法加载，解决方案正在找。

```
root@slackware64-current:/tmp/SBo/libxkbcommon-0.2.0# ldd /usr/lib64/qt5/plugins/platforms/libqxcb.so | grep not
    libxkbcommon-x11.so.0 => not found
root@slackware64-current:/tmp/SBo/libxkbcommon-0.2.0# grep libxkbcommon-x11 /var/log/packages/libxkbcommon-0.2.0-x86_64-1_SBo 
root@slackware64-current:/tmp/SBo/libxkbcommon-0.2.0# echo $?
1
root@slackware64-current:/tmp/SBo/libxkbcommon-0.2.0# 
```

**Comment by lteyang** [comment]
@Arondight 无效，重新编译qt5也是如此，也试了安装 ffmpeg,gst-plugins-ffmpeg 也无效，没思路了，不过倒是可以看MV...这样还不如用网页...我通过软件发了反馈给官方了，看他们会回复否

**Comment by Arondight** [comment]
@lteyang 那应该就是缺kreadconfig5 了，我过几天试试吧，感觉能编出来

需要做俩Build，一个是cmake_extra 啥的，还有一个是kreadconfig5

**Comment by lteyang** [comment]
@Arondight 我觉得不是，你是怎么得到这个依赖缺失的？我原来的系统是debian，没有kde，用netease-cloud-music 1.0.0 这个版本运行良好，所以我觉得关系不大

**Comment by Arondight** [comment]
@lteyang 控制台输出，需要使用kreconfig5 指令，这个是kde5 的组件之一，但是不依赖其他kde 组件，可以单独打包。

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/kconfig

只依赖qt5 和extra-cmake-modules，extra-cmake-modules 我看了看，感觉能build

**Comment by Arondight** [comment]
@lteyang 在吗，麻烦pull 一下repo，然后根据README.md 重新build 一次，看看是否运行正常了？

**Comment by Arondight** [comment]
Slackware 14.2 测试通过，Close。
