### ISSUE TITLE
上游新版发布

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/netease_cloud_music_slackbuild#15]
http://s1.music.126.net/download/pc/netease-cloud-music_0.9.0-2_amd64.deb

http://s1.music.126.net/download/pc/netease-cloud-music_0.9.0-2_i386.deb

**Comment by nnnewb** [comment]
get.你修或者我晚上修吧。

**Comment by Arondight** [comment]
提上之后，晚上可能还得测一下……我有current64 的环境
