### ISSUE TITLE
kreadconfig5 依赖缺失

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/netease_cloud_music_slackbuild#22]
导致播放音乐时网络错误

Ref #13 

尝试使用Ubuntu 14.04 的deb 包，无果可能会放弃该项目。

**Comment by Arondight** [comment]
我觉得这项目已经没救了，这是一个KDE5 的组件，使用Ubuntu 14.04 的deb 包，错误依旧

**Comment by Arondight** [comment]
根据Arch Linux 的[PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/kconfig) 编译出错

```
CMake Warning at CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 5.23.0) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- 
 * ECM (required version >= 5.23.0) , Extra CMake Modules. , <https://projects.kde.org/projects/kdesupport/extra-cmake-modules>

CMake Error at /usr/share/cmake-3.5/Modules/FeatureSummary.cmake:556 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:8 (feature_summary)


-- Configuring incomplete, errors occurred!
See also "/tmp/kconfig-5.23.0/build/CMakeFiles/CMakeOutput.log".
```

可能和CMake 的打包有关

**Comment by lteyang** [comment]
我觉得是alien为了兼容性问题，考滤到[note3](https://slackbuilds.org/repository/14.2/libraries/qt5/)，没有把proprietary media codecs编译进去。应该是codecs问题，还是等我编译完再说。。。

**Comment by Arondight** [comment]
恩，加个环境变量解决最好

**Comment by Arondight** [comment]
@lteyang 关于`could not find or load the Qt platform plugin "xcb"` 的报错参见 #21

**Comment by lteyang** [comment]
@Arondight 我这边装了SBo上的libxkbcommon后就没有这个报错，那个我已经看了，可能你是装了两个版本xcb-xkb的原因

**Comment by Arondight** [comment]
@lteyang 0 0 可能是我的系统让我弄得太乱了，如果没有这个错误的话我就关掉了

**Comment by Arondight** [comment]
@lteyang 话说我看了下SBo 上编出来的包确实没这个库啊，你看看这个库属于哪个包的？

``` bash
slackpkg file-search libxkbcommon-x11.so.0
```

或者

``` bash
grep -rns 'libxkbcommon-x11.so.0' /var/log/packages
```

**Comment by lteyang** [comment]
@Arondight 就是SBo上的那个libxkbcommon-0.5.0包：
/var/log/packages/libxkbcommon-0.5.0-x86_64-1_SBo:usr/lib64/libxkbcommon-x11.so.0.0.0

**Comment by Arondight** [comment]
@lteyang 爆炸，那可能是我没同步SBo，我这里libxkbcommon 的版本是0.2

**Comment by lteyang** [comment]
@Arondight 那个可以同步么，我都不知道怎么加库，我就是手动下载下来安装的

**Comment by Arondight** [comment]
@lteyang [sbopkg/sbopkg](https://github.com/sbopkg/sbopkg)

**Comment by lteyang** [comment]
@Arondight 看着还在测试阶段，我还是用老办法在线下载吧，因为有的包在墙外

**Comment by Arondight** [comment]
https://github.com/slackwarecn/kconfig
