### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/netease_cloud_music_slackbuild#4]
1. 下载deb 应该是build 脚本完成的事情，不应该由用户来完成
2. 设置高版本glibc 应该是用户完成的事情，不应该由build 脚本来完成

建议放弃兼容14.1，现在14.2 马上出来了，current 过了即可。对应地slackbuilds.org 上只提交14.2+ 版本。

**Comment by nnnewb** [comment]
关于deb，我是参考slackbuilds.org的做法，deb对应源码，所以应由用户下载。

glib版本的问题我也是无奈，毕竟不能要求云音乐用户必须勇敢的上current吧？前几天我升级current结果炸了两次。所以折中一下，仅仅是使用了current的两个so。用源码编译应该更好，但是也会出现不同版本的依赖glib的组件一起跑的情况。由于current的包能直接用所以就没加编译。等14.2出来之后就不用这么丑陋的修补方法了吧，大概。

**Comment by Arondight** [comment]
deb 应当是定死的啊……在所有发行版中的build 系统中source 都应当是写死的，用户下载会有很多麻烦

**Comment by Arondight** [comment]
我过会提一个merge request，你看下是不是合心意，主要把源文件给扔到slackbuild 里面了。

**Comment by nnnewb** [comment]
呃，我不是很明白，在build脚本里我已经是写死了deb的文件名了，虽然说没校验

**Comment by nnnewb** [comment]
好的，不过我恐怕要晚上才能看到了，白天还得搬砖。

**Comment by Arondight** [comment]
_(:з」∠)_ 我搬砖的活比较轻松，白天上班也是没事干……
