### ISSUE TITLE
chown 试图将文件所有者修改为root

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/netease_cloud_music_slackbuild#6]
[cloud_music.SlackBuild L89](https://github.com/slackwarecn/netease_cloud_music_slackbuild/blob/1eb5e708f90b809d15b4598205221df7c68a1af5/cloud_music.SlackBuild#L89)

有两点原因不能这样做：
1. 修改属主为root 要求操作本身具有root 权限。
2. build 脚本绝不应该使用root 权限执行。

**Comment by nnnewb** [comment]
slackbuilds.org提供的SlackBuild模版中就是这么写哒。
这么改也没问题，毕竟deb打包的时候应该已经设置好权限了。
话说回来，事实上SlackBuild脚本都是需要root执行的吧……

**Comment by Arondight** [comment]
0 0 slackbuild 脚本不可以用普通用户跑么
