### ISSUE TITLE
第三方glibc2 二进制包在current 分支上拉取

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/netease_cloud_music_slackbuild#9]
**current 分支是滚动的。**

是否可以考虑放弃对Slackware 14.1 的支持？14.2 也没几天了

Ref #4

**Comment by nnnewb** [comment]
glib没那么容易滚，所以可以比较放心使用。
然后是，开一个slackware14.1的分支和current的分支吧，稍作改动就能用了。

**Comment by Arondight** [comment]
两个分支倒是不用，这个可以等14.2 出来，然后build 脚本里判断（awk）下如果当前版本低于14.2 就自动从14.2 的源里拉下来一个glibc2。

**Comment by Arondight** [comment]
不过好像稳定分支的源里glibc 也是会变的，这就很尴尬了……

**Comment by Arondight** [comment]
我感觉[现在的状态](https://github.com/slackwarecn/netease_cloud_music_slackbuild/tree/9b7181811ef9ad878857234a227654036482a3ad)有点不像SlackBuild 了……更加像一个打包脚本了……感觉还是按照SlackBuild 约定俗成的一套来比较好，这样也好提交到SlackBuilds.org。

感觉入口最好变为`cloud_music.SlackBuild`。

**Comment by Arondight** [comment]
另外就是glib 的问题，这个感觉还是扔给用户为妙，彻底放弃14.1 的兼容，只做14.2。因为过不了多久这个Build 就很难有人及时维护了，或者说有人维护也无法注意到glib 变化这种细节，整个build 脚本就废了。

我没有用过SlackBuild，不过用过不少rpm、deb 和abs，感觉就其他发行版的打包标准来说：
1. 构建过程中绝不应该用到root 权限
2. 源文件需要构建中自动处理
3. 构建过程中绝不应该绕过包管理器自动构建依赖

**Comment by nnnewb** [comment]
SlackBuild的风格的话一般不会脚本自己下包的吧？
我是特意把下载的部分分出来的。

**Comment by nnnewb** [comment]
这是slackbuild的风格问题，你看下slackbuilds.org/faq，里面提到的how to use和slackbuild script template，最初版我是直接改自autotool的template的。

**Comment by nnnewb** [comment]
关于glib的问题，我有个主意，你可以把glib的patch部分从SlackBuild里面提取出来另外放一个脚本，建分支放slackware14.1-glib2-patch里。

这样的话能直接给14.2兼容，也能让14.1继续用。
